# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 04 Dec 2020 16:23:48 +0000
*               @ALL          1
*               @user         8
