<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: crashtest
 * Date: Sat, 19 Dec 2020 17:59:28 +0000
 */

$conf['title'] = 'omv-extras.org';
$conf['template'] = 'bootstrap3';
$conf['license'] = 'cc-by-sa';
$conf['breadcrumbs'] = 0;
$conf['youarehere'] = 1;
$conf['tocminheads'] = '2';
$conf['maxtoclevel'] = '5';
$conf['maxseclevel'] = '4';
$conf['sneaky_index'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['htmlok'] = 1;
$conf['jpg_quality'] = 100;
$conf['proxy']['user'] = 'crashtest';
$conf['proxy']['pass'] = '<b>OGNrSndiWU15ck4=';
$conf['plugin']['translation']['dropdown'] = 1;
$conf['plugin']['translation']['display'] = 'langcode,flag,title';
$conf['plugin']['translation']['redirectstart'] = 1;
$conf['plugin']['translation']['checkage'] = 1;
$conf['tpl']['bootstrap3']['socialShareProviders'] = 'facebook,linkedin,pinterest,whatsapp,reddit,twitter,telegram,yammer,google-plus';
$conf['tpl']['arctic']['left_sidebar_content'] = 'main,toc';
$conf['tpl']['argon']['hideTools'] = '1';
